"""
Email formatter — converts consolidated markdown report to plain text + HTML.

Produces a multipart email body for AWS SES delivery.
"""

from __future__ import annotations

import re
from datetime import datetime

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  body {{ font-family: 'Courier New', Courier, monospace; font-size: 13px;
          line-height: 1.5; color: #222; max-width: 680px; margin: 0 auto;
          padding: 20px; }}
  h1 {{ font-size: 16px; border-bottom: 2px solid #333; padding-bottom: 6px; }}
  h2 {{ font-size: 14px; border-bottom: 1px solid #999; padding-bottom: 4px; margin-top: 20px; }}
  table {{ border-collapse: collapse; width: 100%; margin: 10px 0; }}
  th, td {{ border: 1px solid #ccc; padding: 4px 8px; text-align: left; }}
  th {{ background: #f0f0f0; }}
  .buy {{ color: #006600; font-weight: bold; }}
  .sell {{ color: #990000; font-weight: bold; }}
  .hold {{ color: #555; }}
  .stale {{ color: #cc6600; }}
  .footer {{ margin-top: 30px; font-size: 11px; color: #888; border-top: 1px solid #ccc;
             padding-top: 10px; }}
  pre {{ background: #f8f8f8; padding: 10px; border-radius: 4px; overflow-x: auto; }}
  code {{ font-family: 'Courier New', monospace; }}
</style>
</head>
<body>
{body}
<div class="footer">Generated by alpha-engine-research | {timestamp}</div>
</body>
</html>
"""


def _md_to_html(md: str) -> str:
    """
    Lightweight markdown-to-HTML conversion for email.
    Handles headers, bold, bullet lists, horizontal rules, and tables.
    """
    lines = md.split("\n")
    html_lines = []
    in_table = False
    in_list = False

    for line in lines:
        # Horizontal rule
        if re.match(r"^─{3,}$|^-{3,}$|^={3,}$", line.strip()):
            if in_list:
                html_lines.append("</ul>")
                in_list = False
            if in_table:
                html_lines.append("</table>")
                in_table = False
            html_lines.append("<hr>")
            continue

        # Table rows
        if "|" in line and not line.strip().startswith("#"):
            if not in_table:
                html_lines.append("<table>")
                in_table = True
            cells = [c.strip() for c in line.strip().strip("|").split("|")]
            # Detect separator row
            if all(re.match(r"[-:]+$", c.replace(" ", "")) for c in cells if c):
                html_lines.append("<thead><tr>" + "".join("<th></th>" for _ in cells) + "</tr></thead><tbody>")
                continue
            tag = "th" if html_lines and "<table>" in html_lines[-1] else "td"
            row = "".join(f"<{tag}>{_inline_md(c)}</{tag}>" for c in cells)
            html_lines.append(f"<tr>{row}</tr>")
            continue
        else:
            if in_table:
                html_lines.append("</tbody></table>")
                in_table = False

        # Headers
        m = re.match(r"^(#{1,3})\s+(.+)$", line)
        if m:
            if in_list:
                html_lines.append("</ul>")
                in_list = False
            level = len(m.group(1)) + 1  # h2, h3, h4
            html_lines.append(f"<h{level}>{_inline_md(m.group(2))}</h{level}>")
            continue

        # Bullet lists
        m = re.match(r"^[•\-\*]\s+(.+)$", line)
        if m:
            if not in_list:
                html_lines.append("<ul>")
                in_list = True
            html_lines.append(f"<li>{_inline_md(m.group(1))}</li>")
            continue
        else:
            if in_list:
                html_lines.append("</ul>")
                in_list = False

        # Empty line
        if not line.strip():
            html_lines.append("<br>")
            continue

        # Plain paragraph
        html_lines.append(f"<p>{_inline_md(line)}</p>")

    if in_list:
        html_lines.append("</ul>")
    if in_table:
        html_lines.append("</tbody></table>")

    return "\n".join(html_lines)


def _inline_md(text: str) -> str:
    """Convert inline markdown (bold, italic, code) to HTML."""
    # Bold + italic
    text = re.sub(r"\*\*\*(.+?)\*\*\*", r"<strong><em>\1</em></strong>", text)
    # Bold
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    # Italic
    text = re.sub(r"\*(.+?)\*", r"<em>\1</em>", text)
    # Code
    text = re.sub(r"`(.+?)`", r"<code>\1</code>", text)
    # Color BUY/SELL/HOLD
    text = re.sub(r"\bBUY\b", '<span class="buy">BUY</span>', text)
    text = re.sub(r"\bSELL\b", '<span class="sell">SELL</span>', text)
    text = re.sub(r"\bHOLD\b", '<span class="hold">HOLD</span>', text)
    text = re.sub(r"⚠stale", '<span class="stale">⚠stale</span>', text)
    return text


def format_email(markdown_report: str, run_date: str) -> tuple[str, str]:
    """
    Convert a markdown report to (html_body, plain_body) tuple.

    Args:
        markdown_report: the consolidated markdown from the consolidator agent
        run_date: YYYY-MM-DD string used in the footer timestamp

    Returns:
        (html_body, plain_body)
    """
    timestamp = datetime.strptime(run_date, "%Y-%m-%d").strftime("%Y-%m-%d")

    html_body_inner = _md_to_html(markdown_report)
    html_body = _HTML_TEMPLATE.format(body=html_body_inner, timestamp=timestamp)

    # Plain text: just strip markdown formatting minimally
    plain_body = re.sub(r"#{1,6}\s+", "", markdown_report)
    plain_body = re.sub(r"\*{1,3}(.+?)\*{1,3}", r"\1", plain_body)
    plain_body = re.sub(r"`(.+?)`", r"\1", plain_body)
    plain_body += f"\n\n---\nGenerated by alpha-engine-research | {timestamp}"

    return html_body, plain_body
