"""One-shot seed generator for ``evals/rag_retrieval_queries.yaml``.

Picks ~30-40 chunks across the 6 categories using deterministic SQL
predicates, constructs plausible queries from chunk metadata + content
snippets, and writes the YAML test set.

Every emitted entry carries a ``note: "AUTOGENERATED …"`` flag so the
operator (Brian) can review + refine before treating the eval results
as load-bearing. The seed is meant as a starting point — domain
expertise replaces, edits, or expands these queries; the harness in
``evals/rag_retrieval.py`` takes the YAML as-is regardless of whether
it was hand-curated or seeded.

Run once after PR 4 merges:

    python scripts/seed_rag_retrieval_queries.py

Re-runnable; overwrites the YAML each time. Don't run after manual
curation has started — your edits will be lost.

Requires ``RAG_DATABASE_URL`` in env or .env.
"""

from __future__ import annotations

import logging
import re
import sys
from pathlib import Path

import psycopg2
import yaml
from dotenv import dotenv_values


logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
)
log = logging.getLogger(__name__)


_REPO_ROOT = Path(__file__).resolve().parent.parent
# Worktree-friendly env lookup: prefer the worktree's own .env, fall
# back to the canonical research-repo .env so the script runs from
# either location without re-copying secrets.
_ENV_CANDIDATES = [
    _REPO_ROOT / ".env",
    Path.home() / "Development" / "alpha-engine-research" / ".env",
]
_OUT_PATH = _REPO_ROOT / "evals" / "rag_retrieval_queries.yaml"


# Per-category SQL — each picks up to ``limit`` chunks meeting category-
# specific shape predicates. ``length(content) BETWEEN N AND M`` filters
# out micro-chunks (signature lines) and macro-chunks (full table-of-
# contents dumps) that make poor test queries either way.
SAMPLES_PER_CATEGORY = 6

_BOILERPLATE_REGEX = (
    r"(furnish them to the SEC|table of contents|incorporated by reference|"
    r"securities act of 1933|exchange act of 1934|well-known seasoned issuer)"
)


def _connect():
    for path in _ENV_CANDIDATES:
        if path.exists():
            url = dotenv_values(path).get("RAG_DATABASE_URL")
            if url:
                log.debug("Using RAG_DATABASE_URL from %s", path)
                return psycopg2.connect(url)
    raise SystemExit(
        "RAG_DATABASE_URL not found in any of: "
        + ", ".join(str(p) for p in _ENV_CANDIDATES)
    )


# ── Per-category samplers ───────────────────────────────────────────────────


def sample_ticker_named_entity(cur) -> list[dict]:
    """10-K Business chunks across diverse industries — query = ticker
    plus a distinctive proper-noun fragment from the chunk content."""
    cur.execute(
        f"""
        SELECT DISTINCT ON (d.ticker)
               c.id, d.ticker, d.doc_type, d.filed_date, c.content
        FROM rag.chunks c
        JOIN rag.documents d ON c.document_id = d.id
        WHERE d.doc_type = '10-K'
          AND c.section_label = 'Business'
          AND length(c.content) BETWEEN 400 AND 1500
          AND c.content !~* '{_BOILERPLATE_REGEX}'
        ORDER BY d.ticker, random()
        LIMIT %s
        """,
        (SAMPLES_PER_CATEGORY,),
    )
    out = []
    for cid, ticker, doc_type, fd, content in cur.fetchall():
        # Extract the first 2-4 word "Title Case" phrase (likely a
        # named entity / product / segment name) for the query.
        match = re.search(r"\b([A-Z][A-Za-z]+(?:\s+[A-Z][A-Za-z]+){1,3})\b", content)
        anchor = match.group(1) if match else "operations"
        query = f"{ticker} {anchor.lower()}"
        out.append(_entry(
            query=query,
            chunk_id=cid,
            category="ticker_named_entity",
            preview=_preview(content),
            note=(
                f"AUTOGENERATED — anchor extracted from chunk: {anchor!r}. "
                f"Verify this 10-K Business chunk is the right answer for "
                f"query={query!r} before trusting the eval result."
            ),
        ))
    return out


def sample_filing_type(cur) -> list[dict]:
    """8-K Item 2.02 (Results of Operations) chunks — keyword-strong queries
    keyed on the filing type + ticker + period anchor."""
    cur.execute(
        f"""
        SELECT DISTINCT ON (d.ticker)
               c.id, d.ticker, d.doc_type, d.filed_date, c.section_label, c.content
        FROM rag.chunks c
        JOIN rag.documents d ON c.document_id = d.id
        WHERE d.doc_type = '8-K'
          AND c.section_label LIKE 'Item 2.02%%'
          AND length(c.content) BETWEEN 300 AND 1000
          AND c.content !~* '{_BOILERPLATE_REGEX}'
        ORDER BY d.ticker, random()
        LIMIT %s
        """,
        (SAMPLES_PER_CATEGORY,),
    )
    out = []
    for cid, ticker, doc_type, fd, sec, content in cur.fetchall():
        quarter = f"Q{(fd.month - 1) // 3 + 1} {fd.year}"
        query = f"{ticker} 8-K results of operations {quarter}"
        out.append(_entry(
            query=query,
            chunk_id=cid,
            category="filing_type",
            preview=_preview(content),
            note=(
                f"AUTOGENERATED — 8-K Item 2.02 (results of operations) "
                f"filed {fd}. Verify this chunk is the canonical results "
                f"announcement for {ticker} that quarter."
            ),
        ))
    return out


def sample_date_range(cur) -> list[dict]:
    """10-Q chunks anchored by their fiscal period — tests overlay of
    date pre-filter onto retrieval ordering."""
    cur.execute(
        f"""
        SELECT DISTINCT ON (d.ticker)
               c.id, d.ticker, d.doc_type, d.filed_date, c.section_label, c.content
        FROM rag.chunks c
        JOIN rag.documents d ON c.document_id = d.id
        WHERE d.doc_type = '10-Q'
          AND length(c.content) BETWEEN 300 AND 1000
          AND c.content !~* '{_BOILERPLATE_REGEX}'
          AND EXTRACT(YEAR FROM d.filed_date) = 2025
        ORDER BY d.ticker, random()
        LIMIT %s
        """,
        (SAMPLES_PER_CATEGORY,),
    )
    out = []
    for cid, ticker, doc_type, fd, sec, content in cur.fetchall():
        quarter = f"Q{(fd.month - 1) // 3 + 1} {fd.year}"
        query = f"{ticker} {quarter} 10-Q financial condition"
        out.append(_entry(
            query=query,
            chunk_id=cid,
            category="date_range",
            preview=_preview(content),
            note=(
                f"AUTOGENERATED — 10-Q filed {fd} ({quarter}). Tests "
                f"date-pre-filter overlay; the chunk should be a "
                f"distinctive {ticker} {quarter} reference."
            ),
        ))
    return out


def sample_quantitative_line_item(cur) -> list[dict]:
    r"""10-Q chunks containing literal $ amounts — keyword-strong queries
    keyed on the dollar context (line-item phrase + ticker)."""
    cur.execute(
        rf"""
        SELECT DISTINCT ON (d.ticker)
               c.id, d.ticker, d.doc_type, d.filed_date, c.content
        FROM rag.chunks c
        JOIN rag.documents d ON c.document_id = d.id
        WHERE d.doc_type IN ('10-Q', '10-K')
          AND length(c.content) BETWEEN 300 AND 1200
          AND c.content ~ '\$[0-9]'
          AND c.content !~* '{_BOILERPLATE_REGEX}'
        ORDER BY d.ticker, random()
        LIMIT %s
        """,
        (SAMPLES_PER_CATEGORY,),
    )
    out = []
    for cid, ticker, doc_type, fd, content in cur.fetchall():
        # Find a $ amount + the 2-3 words before it (likely the line-item).
        match = re.search(r"((?:\b\w+\s+){1,4})\$([0-9][0-9.,]*)", content)
        if match:
            line_item = match.group(1).strip()
            amount = "$" + match.group(2).split(".")[0]
            # Remove leading filler like "of" / "the" / "to" so the query
            # leans on substantive nouns.
            line_item_clean = re.sub(r"^\s*(of|the|to|for|in|at|on|by|and)\s+", "",
                                      line_item, flags=re.IGNORECASE)
            query = f"{ticker} {line_item_clean} {amount}"
        else:
            query = f"{ticker} {doc_type} financial metrics"
        out.append(_entry(
            query=query,
            chunk_id=cid,
            category="quantitative_line_item",
            preview=_preview(content),
            note=(
                f"AUTOGENERATED — line-item extracted via regex from "
                f"chunk content. Verify the dollar context anchors this "
                f"specific chunk vs other {ticker} filings."
            ),
        ))
    return out


def sample_abstract_thesis(cur) -> list[dict]:
    """10-K MD&A or thesis chunks — paraphrase-friendly queries that
    test cosine recall on conceptual content (vector-friendly category)."""
    cur.execute(
        f"""
        SELECT DISTINCT ON (d.ticker)
               c.id, d.ticker, d.doc_type, d.filed_date, c.section_label, c.content
        FROM rag.chunks c
        JOIN rag.documents d ON c.document_id = d.id
        WHERE (d.doc_type = '10-K' AND c.section_label LIKE 'Item 7%%')
           OR (d.doc_type = 'thesis_research')
          AND length(c.content) BETWEEN 400 AND 1500
          AND c.content !~* '{_BOILERPLATE_REGEX}'
        ORDER BY d.ticker, random()
        LIMIT %s
        """,
        (SAMPLES_PER_CATEGORY,),
    )
    out = []
    for cid, ticker, doc_type, fd, sec, content in cur.fetchall():
        # Generic abstract query — tests whether vector cosine surfaces
        # this conceptual chunk despite the query lacking the chunk's
        # literal terms.
        query = f"{ticker} business strategy and competitive position"
        out.append(_entry(
            query=query,
            chunk_id=cid,
            category="abstract_thesis",
            preview=_preview(content),
            note=(
                f"AUTOGENERATED — generic abstract query. Vector-friendly "
                f"category. The query deliberately AVOIDS chunk-literal "
                f"terms so cosine paraphrase has work to do; if pure "
                f"keyword wins on this category that's a signal the seed "
                f"queries are too coupled to literal content (refine)."
            ),
        ))
    return out


def sample_conceptual_narrative(cur) -> list[dict]:
    """8-K material events / acquisitions / strategic announcements —
    queries about industry-shape narratives rather than line items."""
    cur.execute(
        f"""
        SELECT DISTINCT ON (d.ticker)
               c.id, d.ticker, d.doc_type, d.filed_date, c.section_label, c.content
        FROM rag.chunks c
        JOIN rag.documents d ON c.document_id = d.id
        WHERE d.doc_type = '8-K'
          AND (c.section_label LIKE '%%Material Definitive Agreement%%'
               OR c.section_label LIKE '%%Acquisition%%'
               OR c.section_label LIKE '%%Departure%%')
          AND length(c.content) BETWEEN 400 AND 1500
          AND c.content !~* '{_BOILERPLATE_REGEX}'
        ORDER BY d.ticker, random()
        LIMIT %s
        """,
        (SAMPLES_PER_CATEGORY,),
    )
    out = []
    for cid, ticker, doc_type, fd, sec, content in cur.fetchall():
        # Map section to a narrative theme.
        if "Acquisition" in sec:
            theme = "acquisition"
        elif "Departure" in sec:
            theme = "executive transition"
        else:
            theme = "material agreement"
        query = f"{ticker} {theme} strategic rationale"
        out.append(_entry(
            query=query,
            chunk_id=cid,
            category="conceptual_narrative",
            preview=_preview(content),
            note=(
                f"AUTOGENERATED — 8-K {sec[:60]!r}. Theme-anchored query "
                f"(theme={theme!r}). Tests whether retrieval surfaces the "
                f"narrative event chunk on a paraphrase-style query."
            ),
        ))
    return out


# ── Helpers ─────────────────────────────────────────────────────────────────


def _preview(content: str) -> str:
    """Single-line 200-char preview for the YAML note field."""
    return re.sub(r"\s+", " ", content)[:200]


def _entry(*, query, chunk_id, category, preview, note) -> dict:
    return {
        "query": query,
        "expected_chunk_ids": [str(chunk_id)],
        "category": category,
        "note": f"{note} | preview: {preview!r}",
    }


# ── Main ────────────────────────────────────────────────────────────────────


def main() -> int:
    log.info("Connecting to Neon prod RAG DB...")
    conn = _connect()
    try:
        with conn.cursor() as cur:
            queries: list[dict] = []
            for sampler in (
                sample_ticker_named_entity,
                sample_filing_type,
                sample_date_range,
                sample_quantitative_line_item,
                sample_abstract_thesis,
                sample_conceptual_narrative,
            ):
                rows = sampler(cur)
                log.info("Sampled %d %s chunks", len(rows), sampler.__name__)
                queries.extend(rows)
    finally:
        conn.close()

    log.info("Total seed queries: %d (target 30-50)", len(queries))

    header = (
        "# RAG retrieval eval — hand-curated test set (seeded run)\n"
        "#\n"
        f"# Seeded {len(queries)} queries via scripts/seed_rag_retrieval_queries.py\n"
        "# against the live prod Neon corpus. Every entry carries\n"
        "# `note: \"AUTOGENERATED ...\"` — verify the chunk_id is the right\n"
        "# answer for the query before trusting the eval results. Replace,\n"
        "# refine, or expand to taste.\n"
        "#\n"
        "# Categories (match evals.rag_retrieval.CATEGORIES):\n"
        "# - ticker_named_entity     queries leaning on company / brand / drug names\n"
        "# - filing_type             queries that key on 10-K / 10-Q / 8-K shape\n"
        "# - date_range              queries with a temporal anchor\n"
        "# - quantitative_line_item  queries asking about $ / % / ratio line items\n"
        "# - abstract_thesis         queries about competitive moat / management\n"
        "# - conceptual_narrative    queries about strategic events / narratives\n"
        "#\n"
        "# Run after curation:\n"
        "#   python scripts/run_rag_retrieval_eval.py\n"
        "\n"
    )
    body = yaml.safe_dump(
        {"queries": queries},
        sort_keys=False,
        default_flow_style=False,
        allow_unicode=True,
        width=120,
    )
    _OUT_PATH.write_text(header + body)
    log.info("Wrote %s (%d bytes)", _OUT_PATH, _OUT_PATH.stat().st_size)
    return 0


if __name__ == "__main__":
    sys.exit(main())
